Test1
leesanghyun0414/StudyGroup pull request #1
Opened 2021-03-23 13:57 UTC by sonoda0529

2021-03-23 14:58 UTC, haruto-tsuyuri approved these changes

2021-03-23 14:58 UTC, haruto-tsuyuri commented on html/test.html
> +    <p>お問い合わせ先選択
Pたぐはなぜ？

2021-03-23 14:58 UTC, haruto-tsuyuri commented on html/test.html
> +  <textarea name="message" id="message">メッセージを入力</textarea>
メッセージを入力のテキストがクリックした後も消えない

＞＞

2021-03-23 14:58 UTC, haruto-tsuyuri commented on html/test.html
> +    <p>お問い合わせ先選択
お問い合わせdivタグに classを指定して cssでpaddingを付与

2021-03-23 15:25 UTC, sonoda0529 commented on html/test.html
> +  <textarea name="message" id="message">メッセージを入力</textarea>
できた！

2021-03-23 15:25 UTC, sonoda0529 commented on html/test.html
> +    <p>お問い合わせ先選択
できた！

2021-03-24 09:21 UTC, haruto-tsuyuri requested changes

2021-03-24 09:21 UTC, haruto-tsuyuri commented on css/style.css
> +.message{ padding: 30px;}
paddingは 上のみ必要なのでは？

(Hint : padding-top )

2021-04-07 13:52 UTC, merged